p.on("error", (e) => {
    console.log("error", e)
  })